config/routes.rb
Rails.application.routes.draw do
  resources :discover, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/discover_controller.rb
class DiscoverController < ApplicationController
  def index
    if params[:search]
      @results = DiscoverRecipesFacade.get_results(params[:search])
    end
  end
  def show
    @recipe = RecipeResultsFacade.get_recipe(params[:id])
  end
end

app/controllers/discover_controller.rb.rb
class DiscoverController < ApplicationController
  def index
    if params[:search]
      @results = DiscoverRecipesFacade.get_results(params[:search])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/discover/index.html.erb
<%= form_with url: discover_index_path, local: true, method: :get do |form| %>
  <%= form.label :search, 'Find recipes by listing your ingredients seperated by a comma' %>
  <%= form.text_field :search %>
  <%= form.submit 'Find Recipes' %>
<% end %>

<% if @results %>
  <h4>Results: <%= @results.count %></h4>
  <% @results.each do |result| %>
    <div id=<%= result.id %> >
    <p>Name: <%= result.name %></p>
    <img src=<%= result.img %> style="width:150px;height:150;">
    <p><%= result.missing_ingr_count %> missing ingredients: </p>
      <% result.missing_ingr.each do |ingr| %>
        <p> <%= ingr[:amount] %> <%= ingr[:unit] %> <%= ingr[:name] %> </p>
      <% end %>
    <br>
    </div>
  <% end %>
<% end %>

app/views/discover/show.html.erb
<h3><%= @recipe.title %></h3>
<%= image_tag "#{@recipe.image}" %>
<h5>Time to cook: <%= @recipe.ready_in_minutes %></h5>

<h5>Ingredients: </h5>
<% @recipe.extended_ingredients.each do |ingredient| %>
    <p><%= ingredient[:name] %> <%= ingredient[:amount] %> <%= ingredient[:unit] %></p>
<% end %>
<h5>Instructions: </h5>
<p><%= @recipe.instructions %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BabeWhatsForDinner</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>